AWSTemplateFormatVersion: '2010-09-09'
Description: Simple API Gateway and Lambda setup using CloudFormation

Resources:
  SimpleLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SimpleLambdaFunction
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: my-lambda-code-bucket
        S3Key: lambda-code.zip
      MemorySize: 128
      Timeout: 10
      Role: 
        !Sub 'arn:aws:iam::${AWS::AccountId}:role/SimpleLambdaExecutionRole'
      Environment:
        Variables:
          ExampleVariable: "example-value"
  
  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: SimpleApiGateway
 # Define the API Gateway
  MyApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt MyApiGateway.RootResourceId
      RestApiId: !Ref MyApiGateway
      PathPart: 'simple-api'
  # Define the method for the API resource
  MyApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApiGateway
      ResourceId: !Ref MyApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SimpleLambdaFunction.Arn}/invocations"
  # permision to invoke the Lambda function from API Gateway
  # LambdaInvokePermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !Ref SimpleLambdaFunction
  #     Action: lambda:InvokeFunction
  #     Principal: apigateway.amazonaws.com
  #     SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApiGateway}/*/GET/simple-api"
  # SimpleLambdaExecutionRole:
  # Resources:
  # SimpleLambdaExecutionRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: SimpleLambdaExecutionRole
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: lambda.amazonaws.com
  #           Action: sts:AssumeRole
  #     Policies:
  #       - PolicyName: LambdaBasicExecutionPolicy
  #         PolicyDocument:
  #           Version: "2012-10-17"
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - logs:CreateLogGroup
  #                 - logs:CreateLogStream
  #                 - logs:PutLogEvents
  #               Resource: "*"

